# Microprofile server properties
server:
  port: 8080
  host: 0.0.0.0

# Change the following to true to enable the optional MicroProfile Metrics REST.request metrics
metrics:
  rest-request:
    enabled: false

# Application properties. This is the default greeting
app:
  greeting: Hello

# Datasource properties
javax:
  sql:
    DataSource:
      CountryDS:
        dataSourceClassName: oracle.jdbc.pool.OracleDataSource
        dataSource:
          url: jdbc:oracle:thin:@shukawamatp_high?TNS_ADMIN=/home/shukawam/work/wallet/Wallet_shukawamatp
          user: shukawam
          password: jnfRX&Na0001